name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: docker build . --file Dockerfile --tag vfb-solr:${GITHUB_REF#refs/heads/}
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: virtualflybrain/vfb-solr
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
